services:
  dev-postgres:
    image: postgres:15.7-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: hoge
      POSTGRES_PASSWORD: hoge
      POSTGRES_DB: hoge
    restart: always
    networks:
      - fuga
networks:
  fuga:
